# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: |
            sudo apt-get update
            sudo apt-get install -y cmake build-essential pkg-config
            sudo apt-get install -y libwayland-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxkbcommon-dev
            sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
            sudo apt-get install -y libpulse-dev libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
            
    - name: Build
      run: ${{github.workspace}}/build.sh

    - name: Test
      working-directory: ${{github.workspace}}/bin
      run: array_example -C ${{env.BUILD_TYPE}}
